version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./client
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
